"""initial schema: raw ingestion tables, outbox, reconciliation results, exceptions

Revision ID: 0001
Revises:
Create Date: 2026-08-18

Hand-written rather than autogenerated. Autogenerate does not emit partial indexes
with the predicates this schema depends on, and those predicates are load-bearing:
they are what make worker idempotency and the sweeper cheap.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


INGEST_SOURCE = postgresql.ENUM("gateway", "ledger", name="ingest_source", create_type=False)
RECON_STATUS = postgresql.ENUM(
    "matched",
    "unmatched_gateway_only",
    "unmatched_ledger_only",
    "duplicate",
    "amount_drift",
    "time_drift",
    name="recon_status",
    create_type=False,
)
MATCH_LAYER = postgresql.ENUM(
    "exact",
    "time_drift",
    "amount_drift",
    "duplicate",
    "unmatched_sweep",
    name="match_layer",
    create_type=False,
)


def upgrade() -> None:
    bind = op.get_bind()
    for enum_type in (INGEST_SOURCE, RECON_STATUS, MATCH_LAYER):
        enum_type.create(bind, checkfirst=True)

    # ------------------------------------------------------------------ gateway
    op.create_table(
        "gateway_transactions",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("txn_id", sa.String(length=128), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("gateway_ref", sa.String(length=128), nullable=False),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("duplicate_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("reconciled_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "currency ~ '^[A-Z]{3}$'", name=op.f("ck_gateway_transactions_currency_iso4217")
        ),
        sa.CheckConstraint(
            "duplicate_count >= 0",
            name=op.f("ck_gateway_transactions_duplicate_count_non_negative"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_gateway_transactions")),
    )
    # Ingestion idempotency: ON CONFLICT (idempotency_key) DO NOTHING targets this.
    op.create_index(
        "uq_gateway_transactions_idempotency_key",
        "gateway_transactions",
        ["idempotency_key"],
        unique=True,
    )
    # Matcher layers 1-3: WHERE txn_id = :t AND occurred_at BETWEEN :lo AND :hi.
    op.create_index(
        "ix_gateway_transactions_txn_id_occurred_at",
        "gateway_transactions",
        ["txn_id", "occurred_at"],
    )
    # Sweeper: oldest rows still awaiting a counterparty. Partial -> index size tracks
    # the pending backlog, not total history.
    op.create_index(
        "ix_gateway_transactions_pending_received_at",
        "gateway_transactions",
        ["received_at"],
        postgresql_where=sa.text("reconciled_at IS NULL"),
    )

    # ------------------------------------------------------------------- ledger
    op.create_table(
        "ledger_entries",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("entry_id", sa.String(length=128), nullable=False),
        sa.Column("txn_id", sa.String(length=128), nullable=False),
        sa.Column("amount", sa.Numeric(precision=18, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("duplicate_count", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "received_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("reconciled_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "currency ~ '^[A-Z]{3}$'", name=op.f("ck_ledger_entries_currency_iso4217")
        ),
        sa.CheckConstraint(
            "duplicate_count >= 0", name=op.f("ck_ledger_entries_duplicate_count_non_negative")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ledger_entries")),
    )
    # Ingestion idempotency, ledger side.
    op.create_index(
        "uq_ledger_entries_idempotency_key", "ledger_entries", ["idempotency_key"], unique=True
    )
    # Matcher layers 1-3, ledger side.
    op.create_index(
        "ix_ledger_entries_txn_id_occurred_at", "ledger_entries", ["txn_id", "occurred_at"]
    )
    # Sweeper, ledger side.
    op.create_index(
        "ix_ledger_entries_pending_received_at",
        "ledger_entries",
        ["received_at"],
        postgresql_where=sa.text("reconciled_at IS NULL"),
    )

    # ------------------------------------------------------------------- outbox
    op.create_table(
        "outbox_events",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("source", INGEST_SOURCE, nullable=False),
        sa.Column("row_id", sa.BigInteger(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_events")),
    )
    # Relay poll: WHERE published_at IS NULL ORDER BY id FOR UPDATE SKIP LOCKED.
    op.create_index(
        "ix_outbox_events_unpublished",
        "outbox_events",
        ["id"],
        postgresql_where=sa.text("published_at IS NULL"),
    )

    # -------------------------------------------------- reconciliation results
    op.create_table(
        "reconciliation_results",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("gateway_txn_id", sa.BigInteger(), nullable=True),
        sa.Column("ledger_entry_id", sa.BigInteger(), nullable=True),
        sa.Column("status", RECON_STATUS, nullable=False),
        sa.Column("match_layer", MATCH_LAYER, nullable=False),
        sa.Column(
            "resolved_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("match_latency_ms", sa.Integer(), nullable=True),
        sa.Column("source_message_id", sa.String(length=64), nullable=True),
        sa.CheckConstraint(
            "gateway_txn_id IS NOT NULL OR ledger_entry_id IS NOT NULL",
            name=op.f("ck_reconciliation_results_at_least_one_side"),
        ),
        sa.CheckConstraint(
            "match_latency_ms IS NULL OR match_latency_ms >= 0",
            name=op.f("ck_reconciliation_results_latency_non_negative"),
        ),
        # RESTRICT, not CASCADE: a raw transaction that has been reconciled is
        # evidence. Deleting it out from under its result would rewrite history.
        sa.ForeignKeyConstraint(
            ["gateway_txn_id"],
            ["gateway_transactions.id"],
            name=op.f("fk_reconciliation_results_gateway_txn_id_gateway_transactions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["ledger_entry_id"],
            ["ledger_entries.id"],
            name=op.f("fk_reconciliation_results_ledger_entry_id_ledger_entries"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reconciliation_results")),
    )
    # Worker idempotency: at most one non-duplicate result per raw row, so a
    # redelivered message or a second racing worker hits ON CONFLICT DO NOTHING.
    op.create_index(
        "uq_reconciliation_results_gateway_active",
        "reconciliation_results",
        ["gateway_txn_id"],
        unique=True,
        postgresql_where=sa.text("gateway_txn_id IS NOT NULL AND status <> 'duplicate'"),
    )
    op.create_index(
        "uq_reconciliation_results_ledger_active",
        "reconciliation_results",
        ["ledger_entry_id"],
        unique=True,
        postgresql_where=sa.text("ledger_entry_id IS NOT NULL AND status <> 'duplicate'"),
    )
    # One duplicate marker per raw row; the retry tally lives in duplicate_count.
    op.create_index(
        "uq_reconciliation_results_gateway_duplicate",
        "reconciliation_results",
        ["gateway_txn_id"],
        unique=True,
        postgresql_where=sa.text("gateway_txn_id IS NOT NULL AND status = 'duplicate'"),
    )
    op.create_index(
        "uq_reconciliation_results_ledger_duplicate",
        "reconciliation_results",
        ["ledger_entry_id"],
        unique=True,
        postgresql_where=sa.text("ledger_entry_id IS NOT NULL AND status = 'duplicate'"),
    )
    # GET /v1/transactions?status=&cursor= : keyset pagination on (status, id DESC).
    op.create_index(
        "ix_reconciliation_results_status_id",
        "reconciliation_results",
        ["status", sa.text("id DESC")],
    )
    # GET /v1/stats?window= : range scan on resolved_at plus latency percentiles.
    op.create_index(
        "ix_reconciliation_results_resolved_at", "reconciliation_results", ["resolved_at"]
    )

    # --------------------------------------------------------------- exceptions
    op.create_table(
        "exceptions",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("reconciliation_result_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "opened_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("resolution_notes", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "closed_at IS NULL OR closed_at >= opened_at",
            name=op.f("ck_exceptions_closed_after_opened"),
        ),
        # CASCADE here (unlike the raw tables): an exception has no meaning without
        # the result that opened it.
        sa.ForeignKeyConstraint(
            ["reconciliation_result_id"],
            ["reconciliation_results.id"],
            name=op.f("fk_exceptions_reconciliation_result_id_reconciliation_results"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_exceptions")),
    )
    # One exception per result -> exception creation is ON CONFLICT DO NOTHING.
    op.create_index(
        "uq_exceptions_reconciliation_result_id",
        "exceptions",
        ["reconciliation_result_id"],
        unique=True,
    )
    # GET /v1/exceptions?status=open : the human work queue, keyset on id DESC.
    op.create_index(
        "ix_exceptions_open_id",
        "exceptions",
        [sa.text("id DESC")],
        postgresql_where=sa.text("closed_at IS NULL"),
    )
    # GET /v1/exceptions?status=closed : the audit trail.
    op.create_index(
        "ix_exceptions_closed_id",
        "exceptions",
        [sa.text("id DESC")],
        postgresql_where=sa.text("closed_at IS NOT NULL"),
    )


def downgrade() -> None:
    op.drop_table("exceptions")
    op.drop_table("reconciliation_results")
    op.drop_table("outbox_events")
    op.drop_table("ledger_entries")
    op.drop_table("gateway_transactions")
    bind = op.get_bind()
    for enum_type in (MATCH_LAYER, RECON_STATUS, INGEST_SOURCE):
        enum_type.drop(bind, checkfirst=True)
